name: Build docs

on:
    push: 
        branches: [ $default-branch ]

env:
    APP_NAME: typedoc

permissions:
    contents: write

jobs:
    build:
        name: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build Doc
              run: |
                # Replace with your doc command
                pnpm doc
                curl -O https://gist.githubusercontent.com/gorgeousawakening/efc3c9efacd4241893e19e54787bd7fc/raw/c80c3c7b75d47526dc1de990bff5922e5f942d46/typedoc-fix-cf.mjs
                # Replace docs for your folder path it uses the folder where was downloaded like root path (its a mandatory provide a path)
                node typedoc-fix-cf.mjs docs
    deploy:
        name: deploy-to-pages
        runs-on: ubuntu-latest
        needs: build

        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source
        
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4 
            